apiVersion: v1
kind: Namespace
metadata:
  name: memos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: memos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
        - name: memos
          image: ghcr.io/usememos/memos:0.24.0
          ports:
            - containerPort: 5230
          env:
            - name: MEMOS_MODE
              value: "prod"
            - name: MEMOS_ADDR
              value: "0.0.0.0"
            - name: MEMOS_PORT
              value: "5230"
            - name: MEMOS_DATA
              value: "/var/opt/memos"
          volumeMounts:
            - name: memos-data
              mountPath: /var/opt/memos
      volumes:
        - name: memos-data
          emptyDir: {}   # ephemeral but guaranteed writable
---
apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: memos
spec:
  selector:
    app: memos
  ports:
    - port: 5230
      targetPort: 5230
      protocol: TCP
      name: http
  type: ClusterIP
